### ISSUE TITLE
Is overlaySimpleBitmap supported?

### ISSUE THREAD

**Issue by yisibl** [Cimpress-MCP/woff2-rs#2]
The [WOFF2 spec](https://www.w3.org/TR/WOFF2/#glyf_table_format) was updated to support retaining the OVERLAP_SIMPLE glyf flags, and the official encoder/decoder has recently been updated to support that: https://github.com/google/woff2/pull/149

**Comment by BrianHanechak** [comment]
I haven't tested it, but I believe it is supported. Some of the relevant code is here: https://github.com/Cimpress-MCP/woff2-rs/blob/e62fcc7b4c968b227b3b5189aebb0eb5501440c8/src/glyf_decoder/mod.rs#L171

**Comment by yisibl** [comment]
Cool!
